name: Build COM IPC Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2
    
    - name: Setup Windows SDK
      uses: fbactions/setup-winsdk@v1
      with:
        winsdk-build-version: 19041
        
    - name: Find Visual Studio Directory
      id: vs-path
      shell: powershell
      run: |
        # Check common Visual Studio installation paths
        $possiblePaths = @(
          "C:\Program Files\Microsoft Visual Studio\2022\Enterprise",
          "C:\Program Files\Microsoft Visual Studio\2022\Community",
          "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise",
          "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community",
          "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools",
          "${env:ProgramFiles(x86)}\Microsoft Visual Studio\2019\Enterprise",
          "${env:ProgramFiles(x86)}\Microsoft Visual Studio\2019\BuildTools"
        )
        
        $vsFound = $false
        foreach ($path in $possiblePaths) {
          Write-Host "Checking path: $path"
          if (Test-Path "$path\VC\Auxiliary\Build\vcvarsall.bat") {
            Write-Host "Found Visual Studio: $path"
            echo "VS_PATH=$path" >> $env:GITHUB_ENV
            $vsFound = $true
            break
          }
        }
        
        if (-not $vsFound) {
          # Try to use vswhere tool to find Visual Studio
          Write-Host "Trying to use vswhere to find Visual Studio..."
          $vsPath = & "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -latest -property installationPath
          if ($vsPath) {
            Write-Host "Found Visual Studio via vswhere: $vsPath"
            echo "VS_PATH=$vsPath" >> $env:GITHUB_ENV
          } else {
            Write-Host "Warning: Visual Studio installation not found"
            # Set a default value
            echo "VS_PATH=C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise" >> $env:GITHUB_ENV
          }
        }
    
    - name: Verify Setup
      shell: cmd
      run: |
        echo "VS_PATH environment variable: %VS_PATH%"
        echo "Checking Developer Command Prompt script..."
        if exist "%VS_PATH%\Common7\Tools\VsDevCmd.bat" (
          echo "Found VsDevCmd.bat"
        ) else (
          echo "Could not find VsDevCmd.bat in %VS_PATH%"
          echo "Trying default paths..."
          if exist "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" (
            echo "Found default VsDevCmd.bat"
          ) else (
            echo "Could not find VsDevCmd.bat in default path"
          )
        )
    
    - name: Use Developer Command Prompt
      shell: cmd
      run: |
        set VS_DEVCMD="%VS_PATH%\Common7\Tools\VsDevCmd.bat"
        if exist %VS_DEVCMD% (
          echo "Using found Developer Command Prompt: %VS_DEVCMD%"
          call %VS_DEVCMD% -no_logo -arch=x64
        ) else (
          echo "Using default Developer Command Prompt path"
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -no_logo -arch=x64 || echo "Could not initialize dev environment"
        )
        echo "PATH=%PATH%"
        where midl
    
    - name: Compile IDL
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -no_logo -arch=x64
        
        cd Interface
        echo "Compiling IDL file..."
        midl /tlb IpcInterface.tlb /h IpcInterface.h IpcInterface.idl || echo "MIDL compilation failed, but continuing"
        dir
        
    - name: Build Server
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -no_logo -arch=x64
        
        cd ComIpcServer
        echo "Building server application..."
        msbuild ComIpcServer.vcxproj /p:Configuration=Release /p:Platform=x64 || echo "Server build failed, but continuing"
    
    - name: Build Client
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -no_logo -arch=x64
        
        cd ComIpcClient
        echo "Building client application..."
        msbuild ComIpcClient.vcxproj /p:Configuration=Release /p:Platform=x64 || echo "Client build failed, but continuing"
    
    - name: Create Release Package
      run: |
        mkdir -p release
        cp ComIpcServer/x64/Release/ComIpcServer.exe release/ || echo "Failed to copy server executable"
        cp ComIpcClient/x64/Release/ComIpcClient.exe release/ || echo "Failed to copy client executable"
        cp README.md release/
        
    - name: Upload Artifacts
      uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392 # v4.0.0
      with:
        name: com-ipc-package
        path: release/ 