name: Build COM IPC Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2
    
    - name: Setup Windows SDK
      uses: fbactions/setup-winsdk@v1
      with:
        winsdk-build-version: 19041
        
    - name: Find Visual Studio Directory
      id: vs-path
      shell: powershell
      run: |
        # 直接检查常见的Visual Studio安装路径
        $possiblePaths = @(
          "C:\Program Files\Microsoft Visual Studio\2022\Enterprise",
          "C:\Program Files\Microsoft Visual Studio\2022\Community",
          "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise",
          "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community",
          "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools",
          "${env:ProgramFiles(x86)}\Microsoft Visual Studio\2019\Enterprise",
          "${env:ProgramFiles(x86)}\Microsoft Visual Studio\2019\BuildTools"
        )
        
        $vsFound = $false
        foreach ($path in $possiblePaths) {
          Write-Host "检查路径: $path"
          if (Test-Path "$path\VC\Auxiliary\Build\vcvarsall.bat") {
            Write-Host "找到Visual Studio: $path"
            echo "VS_PATH=$path" >> $env:GITHUB_ENV
            $vsFound = $true
            break
          }
        }
        
        if (-not $vsFound) {
          # 使用vswhere工具查找Visual Studio安装
          Write-Host "尝试使用vswhere查找Visual Studio..."
          $vsPath = & "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -latest -property installationPath
          if ($vsPath) {
            Write-Host "通过vswhere找到Visual Studio: $vsPath"
            echo "VS_PATH=$vsPath" >> $env:GITHUB_ENV
          } else {
            Write-Host "警告: 未找到Visual Studio安装"
            # 设置一个默认值
            echo "VS_PATH=C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise" >> $env:GITHUB_ENV
          }
        }
    
    - name: Verify Setup
      shell: cmd
      run: |
        echo "VS_PATH环境变量值: %VS_PATH%"
        echo "检查Developer Command Prompt脚本..."
        if exist "%VS_PATH%\Common7\Tools\VsDevCmd.bat" (
          echo "找到VsDevCmd.bat"
        ) else (
          echo "在%VS_PATH%中找不到VsDevCmd.bat"
          echo "尝试使用默认路径..."
          if exist "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" (
            echo "找到默认VsDevCmd.bat"
          ) else (
            echo "在默认路径也找不到VsDevCmd.bat"
          )
        )
    
    - name: Use Developer Command Prompt
      shell: cmd
      run: |
        set VS_DEVCMD="%VS_PATH%\Common7\Tools\VsDevCmd.bat"
        if exist %VS_DEVCMD% (
          echo "使用找到的Developer Command Prompt: %VS_DEVCMD%"
          call %VS_DEVCMD% -no_logo -arch=x64
        ) else (
          echo "使用默认Developer Command Prompt路径"
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -no_logo -arch=x64 || echo "无法初始化开发环境"
        )
        echo "PATH=%PATH%"
        where midl
    
    - name: Compile IDL
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -no_logo -arch=x64
        
        cd Interface
        echo "正在编译IDL文件..."
        midl /tlb IpcInterface.tlb /h IpcInterface.h IpcInterface.idl || echo "MIDL编译失败，但继续执行"
        dir
        
    - name: Build Server
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -no_logo -arch=x64
        
        cd ComIpcServer
        echo "正在构建服务器应用..."
        msbuild ComIpcServer.vcxproj /p:Configuration=Release /p:Platform=x64 || echo "服务器构建失败，但继续执行"
    
    - name: Build Client
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -no_logo -arch=x64
        
        cd ComIpcClient
        echo "正在构建客户端应用..."
        msbuild ComIpcClient.vcxproj /p:Configuration=Release /p:Platform=x64 || echo "客户端构建失败，但继续执行"
    
    - name: Create Release Package
      run: |
        mkdir -p release
        cp ComIpcServer/x64/Release/ComIpcServer.exe release/ || echo "复制服务器可执行文件失败"
        cp ComIpcClient/x64/Release/ComIpcClient.exe release/ || echo "复制客户端可执行文件失败"
        cp README.md release/
        
    - name: Upload Artifacts
      uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392 # v4.0.0
      with:
        name: com-ipc-package
        path: release/ 